return {
	{ "LineNr", { fg = "#ffffff" } },
	{ "TelescopeBorder", { fg = "#c4ff4d", bg = "none" } },
	{ "TelescopePromptTitle", { bg = "#ff4d4d", fg = "#000000" } },
	{ "TelescopePreviewTitle", { bg = "#79ff4d", fg = "#000000" } },
	{ "TelescopeResultsTitle", { bg = "#66ffcc", fg = "#000000" } },
	{ "NvimTreeIndentMarker", { fg = "#1affd1", bg = "none" } },
	{ "WinSeparator", { fg = "#ffff4d", bg = "none" } },
	{ "WhichKey", { fg = "#ff00ff", bg = "none" } },
	{ "WhichKeyBorder", { fg = "#ace600", bg = "none" } },
	{ "FloatBorder", { fg = "#e60073", bg = "none" } },
	{ "WildMenu", { fg = "#bf40bf", bg = "none" } },
	{ "NoiceCmdlinePrompt", fg = "none", bg = "#bfff80" },
	{ "NoiceCmdlinePopupBorder", { fg = "#b84dff", bg = "none" } },

	{ "NavicIconsFile", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsModule", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsNamespace", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsPackage", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsClass", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsMethod", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsProperty", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsField", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsConstructor", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsEnum", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsInterface", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsFunction", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsVariable", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsConstant", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsString", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsNumber", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsBoolean", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsArray", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsObject", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsKey", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsNull", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsEnumMember", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsStruct", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsEvent", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsOperator", { bg = "#1a1b26", fg = "none" } },
	{ "NavicIconsTypeParameter", { bg = "#1a1b26", fg = "none" } },
	{ "NavicText", { bg = "#1a1b26", fg = "#b3ff1a" } },
	{ "NavicSeparator", { bg = "#1a1b26", fg = "#ff1a1a" } },

	{ "GitSignsAdd", { fg = "#00e6ac", bg = "none" } },
	{ "GitSignsChange", { fg = "#ffff00", bg = "none" } },
	{ "GitSignsDelte", { fg = "#ff0000", bg = "none" } },
}
