return {
	{ "LineNr", { fg = "#ffffff" } },
	{ "TelescopeBorder", { fg = "#c4ff4d", bg = "none" } },
	{ "TelescopePromptTitle", { bg = "#ff4d4d", fg = "#000000" } },
	{ "TelescopePreviewTitle", { bg = "#79ff4d", fg = "#000000" } },
	{ "TelescopeResultsTitle", { bg = "#66ffcc", fg = "#000000" } },
	{ "NvimTreeIndentMarker", { fg = "#1affd1", bg = "none" } },
	{ "WinSeparator", { fg = "#ffff4d", bg = "none" } },
	{ "WhichKey", { fg = "#ff00ff", bg = "none" } },
	{ "WhichKeyBorder", { fg = "#ace600", bg = "none" } },
	{ "FloatBorder", { fg = "#e60073", bg = "none" } },
	{ "WildMenu", { fg = "#bf40bf", bg = "none" } },
	{ "NoiceCmdlinePrompt", fg = "none", bg = "#bfff80" },
	{ "NoiceCmdlinePopupBorder", { fg = "#b84dff", bg = "none" } },
}
