return {
    {"LineNr", {fg = "#ffffff"}},
    {"TelescopeBorder", {fg = "#c4ff4d", bg = "none"}},
    {"TelescopePromptTitle", {bg = "#ff4d4d", fg = "#000000"}},
    {"TelescopePreviewTitle", {bg = "#79ff4d", fg = "#000000"}},
    {"TelescopeResultsTitle", {bg = "#66ffcc", fg = "#000000"}},
    {"NvimTreeIndentMarker", {fg = "#1affd1", bg = "none"}},
    {"WinSeparator", {fg = "#ffff4d", bg = "none"}},
    {"WhichKey", {fg = "#ff00ff", bg = "none"}},
    {"WhichKeyBorder", {fg = "#ace600", bg = "none"}},
    {"FloatBorder", {fg = "#e60073", bg = "none"}},
    {"WildMenu", {fg = "#bf40bf", bg = "none"}},
    {"NoiceCmdlinePrompt", fg = "none", bg = "#bfff80"},
    {"NoiceCmdlinePopupBorder", {fg = "#b84dff", bg = "none"}},

    {"NavicIconsFile", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsModule", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsNamespace", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsPackage", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsClass", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsMethod", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsProperty", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsField", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsConstructor", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsEnum", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsInterface", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsFunction", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsVariable", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsConstant", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsString", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsNumber", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsBoolean", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsArray", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsObject", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsKey", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsNull", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsEnumMember", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsStruct", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsEvent", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsOperator", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicIconsTypeParameter", {bg = "#1a1b26", fg = "#ffffff"}},
    {"NavicText", {bg = "#1a1b26", fg = "#b3ff1a"}},
    {"NavicSeparator", {bg = "#1a1b26", fg = "#ff1a1a"}},
}
